spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/autoTrade
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/messages


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

upbit:
  url:  ${UPBIT_URL}
  access-key: ${UPBIT_ACCESS_KEY}
  secret-key: ${UPBIT_SECRET_KEY}

binance:
  url: ${BINANCE_URL}
  futures-url: ${BINANCE_FUTURES_URL}
  api-key: ${BINANCE_API_KEY}
  secret-key: ${BINANCE_SECRET_KEY}


resilience4j:
  circuitbreaker:
    instances:
      externalApi:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      externalApi:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException

  timelimiter:
    instances:
      externalApi:
        timeoutDuration: 3s

